export const Colors = {
  primary: '#FF6B9D',
  primaryDark: '#E8547A',
  primaryLight: '#FFE0EC',
  secondary: '#667EEA',
  secondaryLight: '#E8EEFF',
  accent: '#F093FB',
  teal: '#4ECDC4',
  tealLight: '#E0F7F6',
  purple: '#9B59B6',
  purpleLight: '#F0E6F6',
  coral: '#FF8B64',
  coralLight: '#FFF0EB',
  blue: '#4A90D9',
  blueLight: '#EAF3FF',
  success: '#2ECC71',
  successLight: '#E8F9F0',
  warning: '#F39C12',
  warningLight: '#FEF5E7',
  danger: '#E74C3C',
  dangerLight: '#FDEDEC',

  white: '#FFFFFF',
  black: '#1A1A2E',
  gray: '#8E9BB5',
  lightGray: '#E8EDF5',
  veryLightGray: '#F4F6FB',

  background: '#F4F6FB',
  surface: '#FFFFFF',
  card: '#FFFFFF',

  textPrimary: '#1A1A2E',
  textSecondary: '#6B7A99',
  textLight: '#A8B4CC',

  gradientStart: '#FF6B9D',
  gradientEnd: '#667EEA',
};
